/**
 * Shared prepared-material allocation contract.
 *
 * This module is intentionally free of Svelte and server imports so the same
 * normalization and validation rules can run in the form and at save time.
 */

export type AllocationUnit = 'percent' | 'grams';

export type RenderedFatDisposition =
  | 'retain_all'
  | 'discard_all'
  | 'retain_here'
  | 'reserve';

export type ReservedMaterialKind = 'prepared_material' | 'rendered_fat';

export interface AllocationAmount {
  value: number;
  unit: AllocationUnit;
}

/** Canonical ingredient-level removal fields persisted in recipe JSON. */
export interface IngredientRemovalAllocation {
  removedAfterPrep: boolean;
  removalAmount?: number;
  removalUnit?: AllocationUnit;
}

/** Canonical section-level rendered-fat input fields persisted in recipe JSON. */
export interface RenderedFatAllocationInput {
  disposition: RenderedFatDisposition;
  amount?: number;
  unit?: AllocationUnit;
}

/** Calculated rendered-fat ledger for one heated section. */
export interface RenderedFatAllocationResult {
  disposition: RenderedFatDisposition;
  enteredAmount?: number;
  enteredUnit?: AllocationUnit;
  estimatedGrams: number;
  retainedGrams: number;
  reservedGrams: number;
  discardedGrams: number;
  valid: boolean;
  errors: string[];
}

/** One component of an existing Reserved Pool. */
export interface ReservedPoolAllocation {
  kind: ReservedMaterialKind;
  grams: number;
}

/** Pool data used by both the form and save-boundary validation. */
export interface ReservedPoolReference {
  id: string;
  sourceSectionKey: string;
  allocations: ReservedPoolAllocation[];
}

/** Section metadata needed for structural allocation validation. */
export interface AllocationSectionReference {
  key: string;
  prepMethod?: string;
  keepHerePercent?: number;
  outputPoolId?: string;
  reservedPoolId?: string;
  reservedPoolAmount?: AllocationAmount;
  renderedFatAllocation?: RenderedFatAllocationInput;
}

export interface AllocationValidationIssue {
  severity: 'error' | 'warning';
  code:
    | 'duplicate_section'
    | 'duplicate_pool'
    | 'invalid_keep_here'
    | 'missing_output_pool'
    | 'orphan_output_pool'
    | 'orphan_reserved_pool'
    | 'self_pool'
    | 'invalid_pool_grams'
    | 'pool_over_consumed'
    | 'invalid_ingredient_removal'
    | 'rendered_fat_on_unheated_section'
    | 'invalid_rendered_fat_allocation'
    | 'unrepresented_rendered_fat_reservation'
    | 'unused_pool';
  message: string;
  sectionKey?: string;
  poolId?: string;
}

export interface AllocationValidationOptions {
  /** Optional estimated rendered-fat grams by section key. */
  renderedFatEstimates?: Record<string, number>;
  /** Pool ids are generated by the form, but callers may provide a custom set. */
  pools?: ReservedPoolReference[];
}

export interface NormalizedAllocationReferences {
  sections: AllocationSectionReference[];
  pools: ReservedPoolReference[];
}

const HEATED_PREP_METHODS = new Set([
  'parboiled_long_grain_rice',
  'parboiled',
  'boiled',
  'boiled covered',
  'scalded',
  'simmer',
  'sub-simmer',
  'braise',
  'steamed',
  'blanched',
  'baked',
  'baked covered',
  'par-baked',
  'fried',
  'deep-fried',
  'sauteed',
  'stir-fried',
  'pan seared',
  'grilled',
  'broiled',
  'microwave',
]);

const EPSILON = 1e-6;

function finiteNumber(value: unknown): number | undefined {
  const numeric = typeof value === 'number' ? value : Number(value);
  return Number.isFinite(numeric) ? numeric : undefined;
}

function nonNegativeNumber(value: unknown): number | undefined {
  const numeric = finiteNumber(value);
  return numeric !== undefined && numeric >= 0 ? numeric : undefined;
}

function rawRecord(value: unknown): Record<string, unknown> | undefined {
  return value && typeof value === 'object' ? value as Record<string, unknown> : undefined;
}

function rawString(raw: Record<string, unknown>, ...keys: string[]): string | undefined {
  for (const key of keys) {
    const value = raw[key];
    if (typeof value === 'string' && value.trim()) return value.trim();
  }
  return undefined;
}

function normalizeAllocationAmount(raw: unknown): AllocationAmount | undefined {
  const value = rawRecord(raw);
  if (!value) return undefined;
  const numeric = typeof value.value === 'number' ? value.value : Number(value.value);
  if (!Number.isFinite(numeric)) {
    return { value: Number.NaN, unit: normalizeAllocationUnit(value.unit) };
  }
  return { value: numeric, unit: normalizeAllocationUnit(value.unit) };
}

function normalizePoolAllocations(raw: unknown): ReservedPoolAllocation[] {
  if (!Array.isArray(raw)) return [];
  return raw.flatMap((value) => {
    const allocation = rawRecord(value);
    if (!allocation || (allocation.kind !== 'prepared_material' && allocation.kind !== 'rendered_fat')) return [];
    const grams = typeof allocation.grams === 'number' ? allocation.grams : Number(allocation.grams);
    return [{ kind: allocation.kind, grams }];
  });
}

export function normalizeAllocationReferences(rawSections: unknown[]): NormalizedAllocationReferences {
  const sections: AllocationSectionReference[] = [];
  const pools: ReservedPoolReference[] = [];

  for (const value of rawSections) {
    const raw = rawRecord(value);
    if (!raw) continue;
    const key = rawString(raw, 'sectionKey', 'section_key', 'key');
    if (!key) continue;

    const rawKeepHere = raw.keepHerePercent ?? raw.keep_here_percent;
    const keepHerePercent = rawKeepHere === undefined || rawKeepHere === null || rawKeepHere === ''
      ? 100
      : (typeof rawKeepHere === 'number' ? rawKeepHere : Number(rawKeepHere));
    const outputPoolId = rawString(raw, 'outputPoolId', 'output_pool_id');
    const reservedPoolId = rawString(raw, 'reservedPoolId', 'reserved_pool_id');
    const prepMethod = rawString(raw, 'prepMethod', 'prep_method');
    const cookMethod = rawString(raw, 'cookMethod', 'cook_method', 'cookingMethod', 'cooking_method');
    const effectivePrepMethod = prepMethod && prepMethod !== 'none' ? prepMethod : cookMethod;
    const outputPoolAllocations = normalizePoolAllocations(
      raw.outputPoolAllocations ?? raw.output_pool_allocations
    );
    const renderedFatAllocation = normalizeRenderedFatAllocation(raw);
    const renderedFatLedger = rawRecord(raw.renderedFatLedger ?? raw.rendered_fat_ledger);
    const renderedFatReservedGrams = renderedFatLedger
      ? nonNegativeNumber(renderedFatLedger.reservedGrams ?? renderedFatLedger.reserved_grams)
      : undefined;
    if (outputPoolId) {
      const allocations = outputPoolAllocations.slice();
      if (renderedFatReservedGrams !== undefined
        && renderedFatReservedGrams > 0
        && !allocations.some((allocation) => allocation.kind === 'rendered_fat')) {
        allocations.push({ kind: 'rendered_fat', grams: renderedFatReservedGrams });
      }
      pools.push({ id: outputPoolId, sourceSectionKey: key, allocations });
    }

    sections.push({
      key,
      prepMethod: effectivePrepMethod,
      keepHerePercent,
      outputPoolId,
      reservedPoolId,
      reservedPoolAmount: normalizeAllocationAmount(
        raw.reservedPoolAmount ?? raw.reserved_pool_amount
      ),
      renderedFatAllocation,
    });
  }

  return { sections, pools };
}

export function validateRawAllocationSections(rawSections: unknown[]): AllocationValidationIssue[] {
  const references = normalizeAllocationReferences(rawSections);
  return validateAllocationPools(references.sections, { pools: references.pools });
}

export function isHeatedAllocationPrepMethod(prepMethod: unknown): boolean {
  return typeof prepMethod === 'string' && HEATED_PREP_METHODS.has(prepMethod);
}

export function normalizeAllocationUnit(value: unknown, fallback: AllocationUnit = 'percent'): AllocationUnit {
  return value === 'grams' || value === 'g' ? 'grams' : value === 'percent' || value === '%' ? 'percent' : fallback;
}

export function normalizeRenderedFatDisposition(value: unknown): RenderedFatDisposition | undefined {
  if (value === 'retain_all' || value === 'discard_all' || value === 'retain_here' || value === 'reserve') {
    return value;
  }
  return undefined;
}

/**
 * Read the canonical ingredient removal fields while accepting the previous
 * discarded/discardPercent representation during migration.
 */
export function normalizeIngredientRemoval(raw: Record<string, unknown>): IngredientRemovalAllocation {
  const rawRemovedAfterPrep = raw.removedAfterPrep ?? raw.removed_after_prep;
  const removedAfterPrep = typeof rawRemovedAfterPrep === 'boolean'
    ? rawRemovedAfterPrep
    : raw.discarded === true;
  const removalAmount = nonNegativeNumber(
    raw.removalAmount
      ?? raw.removedAmount
      ?? raw.removal_amount
      ?? raw.removed_amount
      ?? (removedAfterPrep ? raw.discardPercent : undefined)
  );
  const removalUnit = normalizeAllocationUnit(
    raw.removalUnit ?? raw.removedAmountUnit ?? raw.removal_unit ?? raw.removed_amount_unit,
    removedAfterPrep ? 'percent' : 'percent'
  );

  return {
    removedAfterPrep,
    removalAmount,
    removalUnit: removalAmount === undefined ? undefined : removalUnit,
  };
}

/** Validate canonical ingredient-removal metadata without requiring cooked grams. */
export function validateRawAllocationIngredients(rawIngredients: unknown[]): AllocationValidationIssue[] {
  const issues: AllocationValidationIssue[] = [];
  for (const value of rawIngredients) {
    const raw = rawRecord(value);
    if (!raw) continue;
    const hasCanonicalField = [
      'removedAfterPrep',
      'removed_after_prep',
      'removalAmount',
      'removedAmount',
      'removal_amount',
      'removed_amount',
      'removalUnit',
      'removedAmountUnit',
      'removal_unit',
      'removed_amount_unit',
    ].some((key) => Object.prototype.hasOwnProperty.call(raw, key));
    if (!hasCanonicalField) continue;

    const rawRemovedAfterPrep = raw.removedAfterPrep ?? raw.removed_after_prep;
    if (rawRemovedAfterPrep !== undefined && typeof rawRemovedAfterPrep !== 'boolean') {
      issues.push({
        severity: 'error',
        code: 'invalid_ingredient_removal',
        message: 'Ingredient removedAfterPrep must be true or false.',
      });
      continue;
    }

    const rawAmount = raw.removalAmount
      ?? raw.removedAmount
      ?? raw.removal_amount
      ?? raw.removed_amount;
    if (rawAmount !== undefined && (finiteNumber(rawAmount) === undefined || Number(rawAmount) < 0)) {
      issues.push({
        severity: 'error',
        code: 'invalid_ingredient_removal',
        message: 'Ingredient removal amount must be a non-negative number.',
      });
    }

    const rawUnit = raw.removalUnit
      ?? raw.removedAmountUnit
      ?? raw.removal_unit
      ?? raw.removed_amount_unit;
    if (rawUnit !== undefined && rawUnit !== 'percent' && rawUnit !== '%' && rawUnit !== 'grams' && rawUnit !== 'g') {
      issues.push({
        severity: 'error',
        code: 'invalid_ingredient_removal',
        message: 'Ingredient removal unit must be percent or grams.',
      });
    }

    const unit = normalizeAllocationUnit(rawUnit);
    if (unit === 'percent' && rawAmount !== undefined && finiteNumber(rawAmount) !== undefined && Number(rawAmount) > 100) {
      issues.push({
        severity: 'error',
        code: 'invalid_ingredient_removal',
        message: 'Ingredient removal percentage cannot exceed 100%.',
      });
    }
  }
  return issues;
}

function legacyRenderedFatInput(raw: Record<string, unknown>): RenderedFatAllocationInput | undefined {
  const legacyDiscardPercent = finiteNumber(raw.discardedFatPercent ?? raw.discarded_fat_percent);
  if (legacyDiscardPercent === undefined || Math.abs(legacyDiscardPercent) <= EPSILON) return undefined;

  const discardPercent = Math.max(0, Math.min(100, legacyDiscardPercent));
  if (discardPercent >= 100 - EPSILON) {
    return { disposition: 'discard_all' };
  }
  return {
    disposition: 'retain_here',
    amount: 100 - discardPercent,
    unit: 'percent',
  };
}

/**
 * Read the canonical section allocation while accepting legacy percentage
 * fields. A legacy 0% discarded value is the old default and is omitted.
 */
export function normalizeRenderedFatAllocation(
  raw: Record<string, unknown>
): RenderedFatAllocationInput | undefined {
  const nested = raw.renderedFatAllocation ?? raw.rendered_fat_allocation;
  if (nested && typeof nested === 'object') {
    const value = nested as Record<string, unknown>;
    const disposition = normalizeRenderedFatDisposition(value.disposition);
    if (disposition) {
      const amount = nonNegativeNumber(value.amount);
      return {
        disposition,
        amount,
        unit: amount === undefined ? undefined : normalizeAllocationUnit(value.unit),
      };
    }
  }

  const directDisposition = normalizeRenderedFatDisposition(
    raw.renderedFatDisposition ?? raw.rendered_fat_disposition
  );
  if (directDisposition) {
    const amount = nonNegativeNumber(raw.renderedFatAmount ?? raw.rendered_fat_amount);
    return {
      disposition: directDisposition,
      amount,
      unit: amount === undefined
        ? undefined
        : normalizeAllocationUnit(raw.renderedFatUnit ?? raw.rendered_fat_unit),
    };
  }

  return legacyRenderedFatInput(raw);
}

export function allocationAmountToGrams(amount: AllocationAmount | undefined, estimateGrams: number): number | undefined {
  if (!amount) return undefined;
  const value = finiteNumber(amount.value);
  if (value === undefined) return undefined;
  return amount.unit === 'percent' ? estimateGrams * value / 100 : value;
}

/**
 * Calculate the four-way rendered-fat ledger. Invalid entered values are
 * reported and capped for display so an in-progress edit never creates a
 * negative discarded amount.
 */
export function calculateRenderedFatAllocation(
  estimatedGrams: number,
  input?: RenderedFatAllocationInput
): RenderedFatAllocationResult {
  const estimate = Math.max(0, finiteNumber(estimatedGrams) ?? 0);
  const disposition = input?.disposition ?? 'retain_all';
  const enteredAmount = finiteNumber(input?.amount);
  const enteredUnit = enteredAmount === undefined ? undefined : normalizeAllocationUnit(input?.unit);
  const errors: string[] = [];

  if (input && !normalizeRenderedFatDisposition(input.disposition)) {
    errors.push('Rendered-fat disposition is invalid.');
  }

  let requestedGrams = estimate;
  if (disposition === 'discard_all') {
    requestedGrams = 0;
  } else if (disposition === 'retain_here' || disposition === 'reserve') {
    if (enteredAmount === undefined) {
      errors.push('A retained or reserved rendered-fat amount is required.');
      requestedGrams = 0;
    } else if (enteredAmount < 0) {
      errors.push('Rendered-fat amount cannot be negative.');
      requestedGrams = 0;
    } else {
      requestedGrams = enteredUnit === 'percent'
        ? estimate * enteredAmount / 100
        : enteredAmount;
    }
  }

  if (requestedGrams > estimate + EPSILON) {
    errors.push('Retained or reserved rendered fat cannot exceed the estimate.');
  }

  const allocatedGrams = Math.max(0, Math.min(estimate, requestedGrams));
  const retainedGrams = disposition === 'reserve' ? 0 : allocatedGrams;
  const reservedGrams = disposition === 'reserve' ? allocatedGrams : 0;
  const discardedGrams = Math.max(0, estimate - retainedGrams - reservedGrams);

  return {
    disposition,
    enteredAmount,
    enteredUnit,
    estimatedGrams: estimate,
    retainedGrams,
    reservedGrams,
    discardedGrams,
    valid: errors.length === 0,
    errors,
  };
}

export function calculateRemovalGrams(
  availablePostPrepGrams: number,
  amount: AllocationAmount | undefined
): { requestedGrams: number; valid: boolean; errors: string[] } {
  const available = Math.max(0, finiteNumber(availablePostPrepGrams) ?? 0);
  const value = finiteNumber(amount?.value);
  const errors: string[] = [];
  if (!amount || value === undefined) {
    return { requestedGrams: 0, valid: false, errors: ['A removal amount is required.'] };
  }
  if (value < 0) errors.push('Removal amount cannot be negative.');
  const requestedGrams = amount.unit === 'percent' ? available * value / 100 : value;
  if (requestedGrams > available + EPSILON) errors.push('Removal amount cannot exceed the prepared ingredient amount.');
  return {
    requestedGrams: Math.max(0, Math.min(available, requestedGrams)),
    valid: errors.length === 0,
    errors,
  };
}

function poolGrams(pool: ReservedPoolReference): number {
  return pool.allocations.reduce((total, allocation) => total + Math.max(0, allocation.grams), 0);
}

function poolAllocationGrams(pool: ReservedPoolReference, kind: ReservedMaterialKind): number {
  return pool.allocations
    .filter((allocation) => allocation.kind === kind)
    .reduce((total, allocation) => total + Math.max(0, allocation.grams), 0);
}

/**
 * Validate pool references and rendered-fat allocation structure. Nutrient
 * estimation is deliberately optional: callers can run this before the
 * nutrition build and pass estimates later for the amount-bound checks.
 */
export function validateAllocationPools(
  sections: AllocationSectionReference[],
  options: AllocationValidationOptions = {}
): AllocationValidationIssue[] {
  const issues: AllocationValidationIssue[] = [];
  const sectionKeys = new Set<string>();
  const pools = options.pools ?? [];
  const poolById = new Map<string, ReservedPoolReference>();
  const poolConsumerCount = new Map<string, number>();
  const requestedByPool = new Map<string, number>();

  for (const section of sections) {
    if (!section.key) continue;
    if (sectionKeys.has(section.key)) {
      issues.push({
        severity: 'error',
        code: 'duplicate_section',
        message: `Section key "${section.key}" is used more than once.`,
        sectionKey: section.key,
      });
    }
    sectionKeys.add(section.key);

    if (section.keepHerePercent !== undefined
      && (!Number.isFinite(section.keepHerePercent) || section.keepHerePercent < 0 || section.keepHerePercent > 100)) {
      issues.push({
        severity: 'error',
        code: 'invalid_keep_here',
        message: 'Keep here must be between 0% and 100%.',
        sectionKey: section.key,
      });
    }

    const hasReservedOutput = typeof section.outputPoolId === 'string' && section.outputPoolId.length > 0;
    if (section.keepHerePercent !== undefined && section.keepHerePercent < 100 && !hasReservedOutput) {
      issues.push({
        severity: 'error',
        code: 'missing_output_pool',
        message: 'A section reserving prepared material must have an output pool.',
        sectionKey: section.key,
      });
    }

    if (section.reservedPoolId) {
      const currentCount = poolConsumerCount.get(section.reservedPoolId) ?? 0;
      poolConsumerCount.set(section.reservedPoolId, currentCount + 1);
      if (section.reservedPoolId === section.outputPoolId) {
        issues.push({
          severity: 'error',
          code: 'self_pool',
          message: 'A section cannot consume its own Reserved Pool.',
          sectionKey: section.key,
          poolId: section.reservedPoolId,
        });
      }
    }

    if (section.renderedFatAllocation) {
      if (!isHeatedAllocationPrepMethod(section.prepMethod)) {
        issues.push({
          severity: 'error',
          code: 'rendered_fat_on_unheated_section',
          message: 'Rendered-fat allocation is only valid on a heated prep section.',
          sectionKey: section.key,
        });
      }
      const hasEstimate = options.renderedFatEstimates
        ? Object.prototype.hasOwnProperty.call(options.renderedFatEstimates, section.key)
        : false;
      const estimate = hasEstimate ? options.renderedFatEstimates![section.key] : 0;
      const result = calculateRenderedFatAllocation(estimate, section.renderedFatAllocation);
      for (const error of result.errors) {
        if (!hasEstimate && error === 'Retained or reserved rendered fat cannot exceed the estimate.') continue;
        issues.push({
          severity: 'error',
          code: 'invalid_rendered_fat_allocation',
          message: error,
          sectionKey: section.key,
        });
      }
      if (section.renderedFatAllocation.unit === 'percent'
        && typeof section.renderedFatAllocation.amount === 'number'
        && section.renderedFatAllocation.amount > 100) {
        issues.push({
          severity: 'error',
          code: 'invalid_rendered_fat_allocation',
          message: 'Rendered-fat percentage cannot exceed 100%.',
          sectionKey: section.key,
        });
      }
      if (result.reservedGrams > EPSILON && !section.outputPoolId) {
        issues.push({
          severity: 'error',
          code: 'unrepresented_rendered_fat_reservation',
          message: 'Reserved rendered fat must be represented in the source section Reserved Pool.',
          sectionKey: section.key,
        });
      }
    }
  }

  for (const pool of pools) {
    if (!pool.id) continue;
    if (poolById.has(pool.id)) {
      issues.push({ severity: 'error', code: 'duplicate_pool', message: `Reserved Pool "${pool.id}" is defined more than once.`, poolId: pool.id });
      continue;
    }
    poolById.set(pool.id, pool);
    if (!sectionKeys.has(pool.sourceSectionKey)) {
      issues.push({
        severity: 'error',
        code: 'orphan_output_pool',
        message: `Reserved Pool "${pool.id}" refers to a missing source section.`,
        poolId: pool.id,
      });
    }
    if (pool.allocations.some((allocation) => !Number.isFinite(allocation.grams) || allocation.grams < 0)) {
      issues.push({
        severity: 'error',
        code: 'invalid_pool_grams',
        message: `Reserved Pool "${pool.id}" contains a negative or invalid allocation.`,
        poolId: pool.id,
      });
    }
  }

  for (const section of sections) {
    if (section.outputPoolId && !poolById.has(section.outputPoolId)) {
      issues.push({
        severity: 'error',
        code: 'orphan_output_pool',
        message: `Section output pool "${section.outputPoolId}" does not exist.`,
        sectionKey: section.key,
        poolId: section.outputPoolId,
      });
    }
    if (section.reservedPoolId) {
      const pool = poolById.get(section.reservedPoolId);
      if (!pool) {
        issues.push({
          severity: 'error',
          code: 'orphan_reserved_pool',
          message: `Reserved Pool "${section.reservedPoolId}" does not exist.`,
          sectionKey: section.key,
          poolId: section.reservedPoolId,
        });
        continue;
      }
      const available = poolGrams(pool);
      const requested = section.reservedPoolAmount
        ? allocationAmountToGrams(section.reservedPoolAmount, available)
        : available;
      if (requested === undefined || requested < 0) {
        issues.push({
          severity: 'error',
          code: 'pool_over_consumed',
          message: `Section consumes more material than Reserved Pool "${pool.id}" provides.`,
          sectionKey: section.key,
          poolId: pool.id,
        });
      } else {
        requestedByPool.set(pool.id, (requestedByPool.get(pool.id) ?? 0) + requested);
      }
    }
  }

  for (const pool of pools) {
    const requested = requestedByPool.get(pool.id) ?? 0;
    const available = poolGrams(pool);
    if (requested > available + EPSILON) {
      issues.push({
        severity: 'error',
        code: 'pool_over_consumed',
        message: `Sections collectively consume more material than Reserved Pool "${pool.id}" provides.`,
        poolId: pool.id,
      });
    }
  }

  for (const pool of pools) {
    const consumers = poolConsumerCount.get(pool.id) ?? 0;
    if (consumers === 0 && poolGrams(pool) > EPSILON) {
      issues.push({
        severity: 'warning',
        code: 'unused_pool',
        message: `Reserved Pool "${pool.id}" is not consumed by any section.`,
        poolId: pool.id,
      });
    }
    // Keep this read explicit: a pool's fat allocation is metadata, not an
    // extra nutrition row. It also makes the shared contract self-documenting.
    poolAllocationGrams(pool, 'rendered_fat');
  }

  return issues;
}
