import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { queryAll } from '$lib/server/turso';
import { RECIPES } from '$lib/data/recipes';
import { RECIPE_NUTRITION } from '$lib/data/recipe-nutrition';

// Pattern that matches auto-generated player IDs like "recipe-1771874787378-e6qosltqx"
const autoIdPattern = /^recipe-\d{10,}-\w+$/i;

export const GET: RequestHandler = async () => {
  // ── 1. Community recipes from Turso (player-submitted, approved) ─────────
  let communityRecipes: object[] = [];
  try {
    const rows = await queryAll(`
      SELECT id, name, nutrition_json
      FROM recipes
      WHERE status = 'approved' AND nutrition_json IS NOT NULL
      ORDER BY name ASC
    `);

    communityRecipes = (rows as Record<string, unknown>[])
      .filter((row) => {
        const name = row.name as string | null;
        return name && name.trim().length > 0 && !autoIdPattern.test(name.trim());
      })
      .map((row) => {
        const nj = JSON.parse(row.nutrition_json as string);
        const gpS: number = nj.gramsPerServing || 100;
        const ps = nj.perServing;
        // Normalise to per-100g so calculateNutrientsForGrams works correctly
        const scale = 100 / gpS;
        return {
          id:             row.id as string,
          name:           row.name as string,
          type:           'community',
          gramsPerServing: gpS,
          servings:       nj.servings as number,
          sources:        nj.sources ?? [],
          cal:  Math.round(ps.cal  * scale * 10) / 10,
          pro:  Math.round(ps.pro  * scale * 10) / 10,
          fat:  Math.round(ps.fat  * scale * 10) / 10,
          carb: Math.round(ps.carb * scale * 10) / 10,
          fib:  Math.round(ps.fib  * scale * 10) / 10,
          h2o:  Math.round(ps.h2o  * scale * 10) / 10,
          sug:  Math.round(ps.sug  * scale * 10) / 10,
        };
      });
  } catch (err) {
    console.error('[/api/recipes/nutrition] turso error:', err);
  }

  // ── 2. Developer recipes from recipe-nutrition.ts (full SR28 micronutrient data) ─
  // All 116 pre-built recipes have a full nutrient profile generated by
  // generate_recipe_nutrition.py from DataCentralCombo dish-level NDB entries.
  const devRecipes = RECIPES
    .filter(r => r.status === 'published' && RECIPE_NUTRITION[r.recipe_id])
    .map(r => {
      const nutrition = RECIPE_NUTRITION[r.recipe_id];
      const ps = nutrition.perServing;
      const gpS = nutrition.gramsPerServing;
      // Normalise to per-100g so calculateNutrientsForGrams works correctly
      const scale = 100 / gpS;
      return {
        id:              `dev-${r.recipe_id}`,
        name:            r.recipe_name,
        type:            'developer',
        gramsPerServing: gpS,
        servings:        nutrition.servings,
        sources:         [{ ndb: nutrition.ndb, name: nutrition.long_desc, grams: gpS }],
        // Legacy 7-macro fields (backward-compatible)
        cal:  Math.round((ps.Energy_KCal  ?? 0) * scale * 10) / 10,
        pro:  Math.round((ps.Protein      ?? 0) * scale * 10) / 10,
        fat:  Math.round((ps.TotalLipidFat ?? 0) * scale * 10) / 10,
        carb: Math.round((ps.Carbohydrate ?? 0) * scale * 10) / 10,
        fib:  Math.round((ps.FiberTotalDietary ?? 0) * scale * 10) / 10,
        h2o:  Math.round((ps.Water        ?? 0) * scale * 10) / 10,
        sug:  Math.round((ps.SugarsTotal  ?? 0) * scale * 10) / 10,
        // Full micronutrient profile (per-100g, all SR28 units)
        micros: nutrition.per100g,
      };
    });

  return json([...communityRecipes, ...devRecipes], {
    headers: {
      'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=60',
    },
  });
};
