// Auto-generated by generate_recipe_nutrition.py — do not edit manually.
// Nutrient values are derived from SR28 DataCentralCombo dish-level NDB entries.
// perServing: nutrients scaled to one serving (portion_grams).
// per100g: nutrients per 100g of finished dish (for display/search normalisation).
// All numerical values in the standard SR28 units (g, mg, µg, kcal, IU).

export interface RecipeNutritionEntry {
  ndb: string;
  long_desc: string;
  cook_method: string | null;
  gramsPerServing: number;
  servings: number;
  perServing: Record<string, number>;
  per100g: Record<string, number>;
}

export const RECIPE_NUTRITION: Record<string, RecipeNutritionEntry> = {
  "SWEET_001": {
    ndb: "18302",
    long_desc: "Pie, apple, prepared from recipe",
    cook_method: "z",
    gramsPerServing: 155.0,
    servings: 1,
    perServing: { Energy_KCal: 410.75, Water: 73.32, Protein: 3.72, TotalLipidFat: 19.38, Carbohydrate: 57.5, FattyAcids_totalSaturated: 4.73, FattyAcids_totalMonounsaturated: 8.35, FattyAcids_totalPolyunsaturated: 5.16, VitaminA_RAE: 17.05, Retinol: 13.95, VitaminC_totalAscorbicAcid: 2.64, Thiamin: 0.22, Riboflavin: 0.16, Niacin: 1.91, PantothenicAcid: 0.14, VitaminB6: 0.05, Folate_total: 37.2, Folate_food: 6.2, Folate_DFE: 58.9, FolicAcid: 31.0, Calcium_Ca: 10.85, Iron_Fe: 1.74, Magnesium_Mg: 10.85, Phosphorus_P: 43.4, Potassium_K: 122.45, Sodium_Na: 327.05, Zinc_Zn: 0.29, Copper_Cu: 0.08, Manganese_Mn: 0.28, Selenium_Se: 12.09, Tryptophan: 0.03, Threonine: 0.09, Isoleucine: 0.12, Leucine: 0.25, Lysine: 0.08, Methionine: 0.06, Cystine: 0.08, Phenylalanine: 0.17, Tyrosine: 0.11, Valine: 0.14, Arginine: 0.14, Histidine: 0.08, Alanine: 0.11, AsparticAcid: 0.17, GlutamicAcid: 1.21, Glycine: 0.12, Proline: 0.42, Serine: 0.17 },
    per100g: { Energy_KCal: 265.0, Water: 47.3, Protein: 2.4, TotalLipidFat: 12.5, Carbohydrate: 37.1, FattyAcids_totalSaturated: 3.05, FattyAcids_totalMonounsaturated: 5.39, FattyAcids_totalPolyunsaturated: 3.33, VitaminA_RAE: 11.0, Retinol: 9.0, VitaminC_totalAscorbicAcid: 1.7, Thiamin: 0.14, Riboflavin: 0.1, Niacin: 1.23, PantothenicAcid: 0.09, VitaminB6: 0.03, Folate_total: 24.0, Folate_food: 4.0, Folate_DFE: 38.0, FolicAcid: 20.0, Calcium_Ca: 7.0, Iron_Fe: 1.12, Magnesium_Mg: 7.0, Phosphorus_P: 28.0, Potassium_K: 79.0, Sodium_Na: 211.0, Zinc_Zn: 0.19, Copper_Cu: 0.05, Manganese_Mn: 0.18, Selenium_Se: 7.8, Tryptophan: 0.02, Threonine: 0.06, Isoleucine: 0.08, Leucine: 0.16, Lysine: 0.05, Methionine: 0.04, Cystine: 0.05, Phenylalanine: 0.11, Tyrosine: 0.07, Valine: 0.09, Arginine: 0.09, Histidine: 0.05, Alanine: 0.07, AsparticAcid: 0.11, GlutamicAcid: 0.78, Glycine: 0.08, Proline: 0.27, Serine: 0.11 },
  },
};
