// Auto-generated by generate_recipe_nutrition.py — do not edit manually.
// Nutrient values are derived from SR28 DataCentralCombo dish-level NDB entries.
// perServing: nutrients scaled to one serving (portion_grams).
// per100g: nutrients per 100g of finished dish (for display/search normalisation).
// All numerical values in the standard SR28 units (g, mg, µg, kcal, IU).

export interface RecipeNutritionEntry {
  ndb: string;
  long_desc: string;
  cook_method: string | null;
  gramsPerServing: number;
  servings: number;
  perServing: Record<string, number>;
  per100g: Record<string, number>;
}

export const RECIPE_NUTRITION: Record<string, RecipeNutritionEntry> = {
  "SWEET_001": {
    ndb: "18302",
    long_desc: "Pie, apple, prepared from recipe",
    cook_method: "z",
    gramsPerServing: 155.0,
    servings: 1,
    perServing: { Energy_KCal: 410.75, Water: 73.32, Protein: 3.72, TotalLipidFat: 19.38, Carbohydrate: 57.5, FattyAcids_totalSaturated: 4.73, FattyAcids_totalMonounsaturated: 8.35, FattyAcids_totalPolyunsaturated: 5.16, VitaminA_RAE: 17.05, Retinol: 13.95, VitaminC_totalAscorbicAcid: 2.64, Thiamin: 0.22, Riboflavin: 0.16, Niacin: 1.91, PantothenicAcid: 0.14, VitaminB6: 0.05, Folate_total: 37.2, Folate_food: 6.2, Folate_DFE: 58.9, FolicAcid: 31.0, Calcium_Ca: 10.85, Iron_Fe: 1.74, Magnesium_Mg: 10.85, Phosphorus_P: 43.4, Potassium_K: 122.45, Sodium_Na: 327.05, Zinc_Zn: 0.29, Copper_Cu: 0.08, Manganese_Mn: 0.28, Selenium_Se: 12.09, Tryptophan: 0.03, Threonine: 0.09, Isoleucine: 0.12, Leucine: 0.25, Lysine: 0.08, Methionine: 0.06, Cystine: 0.08, Phenylalanine: 0.17, Tyrosine: 0.11, Valine: 0.14, Arginine: 0.14, Histidine: 0.08, Alanine: 0.11, AsparticAcid: 0.17, GlutamicAcid: 1.21, Glycine: 0.12, Proline: 0.42, Serine: 0.17 },
    per100g: { Energy_KCal: 265.0, Water: 47.3, Protein: 2.4, TotalLipidFat: 12.5, Carbohydrate: 37.1, FattyAcids_totalSaturated: 3.05, FattyAcids_totalMonounsaturated: 5.39, FattyAcids_totalPolyunsaturated: 3.33, VitaminA_RAE: 11.0, Retinol: 9.0, VitaminC_totalAscorbicAcid: 1.7, Thiamin: 0.14, Riboflavin: 0.1, Niacin: 1.23, PantothenicAcid: 0.09, VitaminB6: 0.03, Folate_total: 24.0, Folate_food: 4.0, Folate_DFE: 38.0, FolicAcid: 20.0, Calcium_Ca: 7.0, Iron_Fe: 1.12, Magnesium_Mg: 7.0, Phosphorus_P: 28.0, Potassium_K: 79.0, Sodium_Na: 211.0, Zinc_Zn: 0.19, Copper_Cu: 0.05, Manganese_Mn: 0.18, Selenium_Se: 7.8, Tryptophan: 0.02, Threonine: 0.06, Isoleucine: 0.08, Leucine: 0.16, Lysine: 0.05, Methionine: 0.04, Cystine: 0.05, Phenylalanine: 0.11, Tyrosine: 0.07, Valine: 0.09, Arginine: 0.09, Histidine: 0.05, Alanine: 0.07, AsparticAcid: 0.11, GlutamicAcid: 0.78, Glycine: 0.08, Proline: 0.27, Serine: 0.11 },
  },
  "SWEET_002": {
    ndb: "18354",
    long_desc: "Strudel, apple",
    cook_method: "z",
    gramsPerServing: 71.0,
    servings: 1,
    perServing: { Energy_KCal: 194.54, Water: 30.88, Protein: 2.34, TotalLipidFat: 7.95, Carbohydrate: 29.18, FiberTotalDietary: 1.56, SugarsTotal: 18.28, Cholesterol: 4.26, FattyAcids_totalSaturated: 1.45, FattyAcids_totalMonounsaturated: 2.31, FattyAcids_totalPolyunsaturated: 3.77, VitaminA_RAE: 4.26, Retinol: 4.26, Carotene_beta: 3.55, VitaminE_alphaTocopherol: 1.01, VitaminK_phylloquinone: 2.06, VitaminC_totalAscorbicAcid: 1.21, Thiamin: 0.03, Riboflavin: 0.01, Niacin: 0.23, PantothenicAcid: 0.19, VitaminB6: 0.03, Folate_total: 19.88, Folate_food: 4.26, Folate_DFE: 31.24, FolicAcid: 15.62, VitaminB12: 0.16, Choline_total: 12.35, LuteinZeaxanthin: 29.82, Calcium_Ca: 10.65, Iron_Fe: 0.3, Magnesium_Mg: 6.39, Phosphorus_P: 23.43, Potassium_K: 105.79, Sodium_Na: 95.85, Zinc_Zn: 0.13, Copper_Cu: 0.02, Manganese_Mn: 0.13, Selenium_Se: 4.33, Tryptophan: 0.02, Threonine: 0.08, Isoleucine: 0.1, Leucine: 0.18, Lysine: 0.11, Methionine: 0.04, Cystine: 0.04, Phenylalanine: 0.11, Tyrosine: 0.08, Valine: 0.11, Arginine: 0.09, Histidine: 0.05, Alanine: 0.08, AsparticAcid: 0.14, GlutamicAcid: 0.6, Glycine: 0.06, Proline: 0.21, Serine: 0.13 },
    per100g: { Energy_KCal: 274.0, Water: 43.5, Protein: 3.3, TotalLipidFat: 11.2, Carbohydrate: 41.1, FiberTotalDietary: 2.2, SugarsTotal: 25.75, Cholesterol: 6.0, FattyAcids_totalSaturated: 2.04, FattyAcids_totalMonounsaturated: 3.26, FattyAcids_totalPolyunsaturated: 5.31, VitaminA_RAE: 6.0, Retinol: 6.0, Carotene_beta: 5.0, VitaminE_alphaTocopherol: 1.42, VitaminK_phylloquinone: 2.9, VitaminC_totalAscorbicAcid: 1.7, Thiamin: 0.04, Riboflavin: 0.02, Niacin: 0.33, PantothenicAcid: 0.27, VitaminB6: 0.04, Folate_total: 28.0, Folate_food: 6.0, Folate_DFE: 44.0, FolicAcid: 22.0, VitaminB12: 0.22, Choline_total: 17.4, LuteinZeaxanthin: 42.0, Calcium_Ca: 15.0, Iron_Fe: 0.42, Magnesium_Mg: 9.0, Phosphorus_P: 33.0, Potassium_K: 149.0, Sodium_Na: 135.0, Zinc_Zn: 0.19, Copper_Cu: 0.03, Manganese_Mn: 0.19, Selenium_Se: 6.1, Tryptophan: 0.03, Threonine: 0.11, Isoleucine: 0.14, Leucine: 0.25, Lysine: 0.15, Methionine: 0.06, Cystine: 0.05, Phenylalanine: 0.15, Tyrosine: 0.11, Valine: 0.16, Arginine: 0.13, Histidine: 0.07, Alanine: 0.11, AsparticAcid: 0.2, GlutamicAcid: 0.84, Glycine: 0.09, Proline: 0.3, Serine: 0.18 },
  },
};
